name: Ansible Playbook

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# on:
#   workflow_dispatch:

on:
  push:
    branches: [ "test" ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  pull_request:
    branches: [ "test" ]
    types: [closed]


# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/mcbtaguiad/ansible:8.7.0
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      volumes:
        - ${{ github.workspace }}:/ansible  
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: pwd
        shell: bash
        run: |
          cd /ansible && ls -lah

      - name: Reset K8S Cluster
        shell: bash
        run: |
          tree /ansible
      

      # - name: Reset K8S Cluster
      #   shell: bash
      #   run: |
      #     ansible-playbook /ansible/playbooks/reset.yaml -i /ansible/inventory/host.yaml

      # - name: Init Cluster
      #   shell: bash
      #   run: |
      #     ansible-playbook /ansible/playbooks/kubeadm_init.yaml -i /ansible/inventory/host.yaml
      
      # - name: Install Components
      #   shell: bash
      #   run: |
      #     ansible-playbook /ansible/playbooks/install_components.yaml -i /ansible/inventory/host.yaml

