name: Build-Push-Deploy

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# on:
#   workflow_dispatch:

on:
  push:
    branches: [ "test" ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  pull_request:
    branches: [ "test" ]
    types: [closed]


# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/mcbtaguiad/ansible:8.7.0
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      volumes:
        - ./:/ansible  
    steps:
      - name: Reset K8S Cluster
        shell: bash
        run: |
          cd /ansible && pwd
      - name: ls
        shell: bash
        run: |
          ls -lah

