name: Ansible Playbook

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# on:
#   workflow_dispatch:

on:
  push:
    branches: [ "test" ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  pull_request:
    branches: [ "test" ]
    types: [closed]


env:
  MASTER1_IP: ${{ secrets.MASTER1_IP }}
  WORKER1_IP: ${{ secrets.WORKER1_IP }}
  # WORKER2_IP: ${{ env.WORKER2_IP }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/mcbtaguiad/ansible:8.7.0
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      volumes:
        - ${{ github.workspace }}:/ansible  
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set host and secret values
        shell: bash
        run: |
          sed -i "s/MASTER1_IP/$MASTER1_IP/g" /ansible/inventory/host.yaml
          sed -i "s/WORKER1_IP/$WORKER1_IP/g" /ansible/inventory/host.yaml
          sed -i "s/SERVER_PASSWORD/$SERVER_PASSWORD/g" /ansible/inventory/group_vars/all.yaml

      - name: Reset K8S Cluster
        shell: bash
        run: |
          ansible-playbook /ansible/playbooks/reset.yaml -i /ansible/inventory/host.yaml

      - name: Init Cluster
        shell: bash
        run: |
          ansible-playbook /ansible/playbooks/kubeadm_init.yaml -i /ansible/inventory/host.yaml
      
      - name: Install Components
        shell: bash
        run: |
          ansible-playbook /ansible/playbooks/install_components.yaml -i /ansible/inventory/host.yaml

