name: Build-Push-Deploy

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# on:
#   workflow_dispatch:

on:
  push:
    branches: [ "test" ]
    # Publish semver tags as releases.
    tags: [ 'v*' ]
  pull_request:
    branches: [ "test" ]
    types: [closed]


# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  ansible-playbook:
    runs-on: ubuntu-latest
    runs-on: docker.io/mcbtaguiad/ansible:8.7.0
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/mcbtaguiad/ansible:8.7.0
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount    
    steps:
      - name: Reset K8S Cluster
        shell: bash
        run: |
          ansible-playbook playbooks/reset.yaml -i inventory/host.yaml

      - name: Init Cluster
        shell: bash
        run: |
          ansible-playbook playbooks/kubeadm_init.yaml -i inventory/host.yaml
      
      - name: Install Components
        shell: bash
        run: |
          ansible-playbook playbooks/install_components.yaml -i inventory/host.yaml

